### ISSUE TITLE
CI: mkosi boot jobs often failing with "TypeError: __init__() got an unexpected keyword argument 'user'"

### ISSUE THREAD

**Issue by solardiz** [lkrg-org/lkrg#187]
These are intermittent errors that have become more frequent lately. I only recall seeing them for mkosi-mainline before, but today they also occurred for the older-Ubuntu tests.

```
Processing triggers for linux-image-unsigned-5.18.0-051800rc6-generic (5.18.0-051800rc6.202205082130) ...
‣ Detaching namespace
‣ Setting up package cache…
‣ Setting up package cache /home/runner/work/lkrg/lkrg/mkosi.cache complete
‣ Setting up temporary workspace.
‣ Temporary workspace set up in /var/tmp/mkosi-3l599leg
‣ Running first (development) stage…
‣  Creating image with partition table…
‣  Created image with partition table as /home/runner/work/lkrg/lkrg/.mkosi-t0kty7k6
‣  Attaching /home/runner/work/lkrg/lkrg/.mkosi-t0kty7k6 as loopback…
‣  Attached /dev/loop3
‣  Formatting root partition…
‣  Mounting image…
‣  Setting up basic OS tree…
‣  Mounting Package Cache
‣  Installing Ubuntu…
‣  Unmounting Package Cache
‣  Mounting Package Cache
‣  Running prepare script…
‣  Unmounting Package Cache
‣  Copying in build script…
‣  Copying in sources…
‣  (Unmounting image)
‣  (Detaching /dev/loop3)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__main__.py", line 36, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__main__.py", line 27, in main
    run_verb(a)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 8058, in run_verb
    manifest = build_stuff(args)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 7419, in build_stuff
    image = build_image(args, root, do_run_build_script=True)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 7166, in build_image
    install_build_src(args, root, do_run_build_script, for_cache)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 3682, in install_build_src
    copy_git_files(args.build_sources, target, source_file_transfer=sft)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 3609, in copy_git_files
    c = run(["git", "-C", src, "ls-files", "-z", *what_files], stdout=PIPE, text=False, user=uid)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/backend.py", line 770, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'user'
Error: Process completed with exit code 1.
```

**Comment by solardiz** [comment]
This isn't even intermittent anymore - they just keep failing upon "Re-run failed jobs".

**Comment by solardiz** [comment]
@vt-alt These just keep failing. Can you please take a look and hopefully fix this at your convenience? Thank you!

**Comment by solardiz** [comment]
I think let's wait a bit for upstream to possibly fix the bug - maybe there's nothing we'll need to do then, and we'll also happen to help them get the fix tested.

Incidentally, I don't understand why this bug initially only manifested itself in our mainline kernel tests. Don't we use the same mkosi version (latest git) in all of our uses of mkosi?

**Comment by vt-alt** [comment]
Breakign commit is merged 4 days ago and I see failed (mkosi) builds appearing since 4 days ago. So I don't see succesful builds which should not be there.

**Comment by solardiz** [comment]
Upstream fixed the issue, I just re-ran the failed jobs - and all are green. Closing. Thank you, @vt-alt!
