### ISSUE TITLE
CI: mkosi-mainline: debootstrap failing

### ISSUE THREAD

**Issue by solardiz** [lkrg-org/lkrg#343]
This started happening today. I tried re-running the job and it just happened again. @vt-alt 

https://github.com/lkrg-org/lkrg/actions/runs/9725918529/job/26843816927

```
I: Configuring bash...
I: Configuring libc-bin...
W: Failure while configuring required packages.
W: See /var/tmp/mkosi-k1r3q4nu/root/debootstrap/debootstrap.log for details (possibly the package base-files is at fault)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__main__.py", line 45, in <module>
    main()
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__main__.py", line 41, in main
    run_verb(a)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 8254, in run_verb
    manifest = build_stuff(config)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 7550, in build_stuff
    image = build_image(state)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 7270, in build_image
    install_distribution(state, cached_tree)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 2979, in install_distribution
    install(state)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 2666, in install_ubuntu
    install_debian_or_ubuntu(state)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 2535, in install_debian_or_ubuntu
    run(cmdline)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/backend.py", line 860, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, env={**os.environ, **env}, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['debootstrap', '--variant=minbase', '--include=ca-certificates', '--merged-usr', '--components=main,universe', '--arch=amd64', 'oracular', '/var/tmp/mkosi-k1r3q4nu/root', 'http://archive.ubuntu.com/ubuntu']' returned non-zero exit status 1.
```

**Comment by solardiz** [comment]
This job was failing for 2 days, but it no longer does for 3 days now. I don't know what changed.

**Comment by vt-alt** [comment]
Ubuntu's debootstrap process seems quite unreliable. Same self-healing is happened with this issue https://github.com/lkrg-org/lkrg/issues/330#issuecomment-2041578430
I think these was repository problems and only thing we could do in such cases it to wait. All simple problems with is we already fixed.

**Comment by solardiz** [comment]
This job is failing again for a few days now, sometimes on debootstrap similarly to the above, other times on not finding gcc-13.

**Comment by solardiz** [comment]
Well, I don't see why it's failing:

```
I: Extracting zlib1g...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__main__.py", line 45, in <module>
    main()
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__main__.py", line 41, in main
    run_verb(a)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 8254, in run_verb
    manifest = build_stuff(config)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 7550, in build_stuff
    image = build_image(state)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 7270, in build_image
    install_distribution(state, cached_tree)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 2979, in install_distribution
    install(state)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 2666, in install_ubuntu
    install_debian_or_ubuntu(state)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 2535, in install_debian_or_ubuntu
    run(cmdline)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/backend.py", line 860, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, env={**os.environ, **env}, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['debootstrap', '--variant=minbase', '--include=ca-certificates', '--merged-usr', '--components=main,universe', '--arch=amd64', 'oracular', '/var/tmp/mkosi-6f1oeip5/root', 'http://archive.ubuntu.com/ubuntu']' returned non-zero exit status 2.
```

Looks different from what was in my first comment here - no `W:` lines and the exit code was 1, now 2.

**Comment by vt-alt** [comment]
I reproduced locally and yes debootstrap just exits `2` without saying anything even with `--verbose`. But there is logfile like `/var/tmp/mkosi-*/root/debootstrap/debootstrap.log` with
```
/usr/local/bin/debootstrap: 178: arithmetic expression: expecting EOF: "baseprog 1"
```
(Perhaps would be good to add printing it.)
```
root@ubuntu-jammy:~/lkrg# cat -n /usr/local/bin/debootstrap | grep -w 178 -5
   173                  else
   174                          WHAT_TO_DO="finddebs dldebs save_variables first_stage"
   175                          fi
   176                  shift
   177                  ;;
   178              --second-stage)
   179                  check_conflicting_option "$1"
   180                  WHAT_TO_DO="second_stage"
   181                  SECOND_STAGE_ONLY=true
   182                  shift
   183                  ;;
```
Looks innocent.

**Comment by vt-alt** [comment]
It appears, that debootstrap process, mkosi relied on, is very fragile.

There is commit with the error
https://git.launchpad.net/ubuntu/+source/debootstrap/commit/?id=21725220e63d98107104a122b4fba868f7f1d802 from 2024-07-26

```diff
@@ -174,7 +175,7 @@ Status: install ok installed" >> "$TARGET/var/lib/dpkg/status"
 	}
 
 	p () {
-		baseprog="$(($baseprog + ${1:-1}))"
+		baseprog="$((baseprog 1))"
 	}
 
 	if ! doing_variant fakechroot; then
```
Another debootstrap bug.

**Comment by vt-alt** [comment]
OK I created a bug report https://bugs.launchpad.net/ubuntu/+source/debootstrap/+bug/2075318

**Comment by solardiz** [comment]
Thank you @vt-alt! So our plan is to wait for debootstrap to fix the issue? Can we maybe switch to using a debootstrap release from prior to this bug?

**Comment by vt-alt** [comment]
Don't know how it worked before but they added `oracular` (which mainline kernels require) on the same day as the breaking change.

**Comment by solardiz** [comment]
Thanks @vt-alt! I re-ran a job https://github.com/lkrg-org/lkrg/actions/runs/10169584324/job/28366227472 and now it failed with:

```
 make[1]: Entering directory '/usr/src/linux-headers-6.11.0-061100rc1daily20240802-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-3ubuntu1) 13.3.0
  You are using:           
  CC [M]  /root/src/src/modules/ksyms/p_resolve_ksym.o
/bin/sh: 1: gcc-13: not found
```

This was also a failure briefly seen just before the latest debootstrap issue.
